on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout kode
        uses: actions/checkout@v4

      - name: Last opp statiske filer
        uses: actions/upload-pages-artifact@v3
        with:
          path: .  # Bruker rotnivået – endre om filene dine ligger i f.eks. ./docs

      - name: Deploy til GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
